### ISSUE TITLE
Assertion error on TOSCA mesh dataset

### ISSUE THREAD

**Issue by dvirginz** [fedassa/SHOT#4]
Thank you very much for making the descriptor open source!
I'm running it on the TOSCA dataset (highly descriptive meshes with over 10000 vertices)
and I'm having an assertion error on some of them:
`void SHOTDescriptor::interpolateSingleChannel(vtkPolyData*, vtkIdList*, const std::vector<double>&, const double*, float*, std::vector<double>&, int, double*): Assertion `(desc_index - 1) * (nr_bins+1) + step_index >= 0 && (desc_index - 1) * (nr_bins+1) + step_index < m_descLength' failed.`

I know that the dataset is valid, and the meshes are fine(I'm able to display them properly using pyMesh.
What can be the problem? what's the logic behind the assertion?

Thanks a lot.

**Comment by samuelesalti** [comment]
Hi Dvir,

the assertion checks if we are going to write beyond the memory limit of the array holding the descriptor. This could be due to a bug in the way we quantize the values to be accumulated in the descriptor, or to some inconsistencies in the input data.

Could you please send to me one of the meshes that is raising the assertion and a snippet describing how you are running the descriptor on it, so that we can try to replicate your issue?

Thanks,
Samuele
